language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then \
       brew update && \
       brew install qt5 && \
       brew link qt5 --force && \
       brew install protobuf && \
       ls -lR /usr/local/include/google/protobuf; \
       which clang++; \
       clang++ -E -x c++ - -v < /dev/null; \
       export CPLUS_INCLUDE_PATH=/usr/local/include; \
       export LIBRARY_PATH=/usr/local/lib; \
     fi"

addons:
  apt:
    packages:
      - qtbase5-dev
      - qtscript5-dev
      - libpcap-dev
      - libprotobuf-dev
      - protobuf-compiler

script:
  - QT_SELECT=qt5 qmake -config debug
  - make

